#!/usr/bin/env python

#  Copyright 2008, Patrick C. McGinty

#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import unittest

mod_to_test = ['test_disc', 'test_parser', 'test_wav', 'test_progress_bar']

def suite():
   # create TestSuite object
   alltests = unittest.TestSuite()
   # load all modules define in the module list
   for module in map(__import__, mod_to_test):
      alltests.addTest(unittest.findTestCases(module))
   return alltests

if __name__ == '__main__':
   unittest.main(defaultTest='suite')

